# Generated by Django 3.2.4 on 2021-06-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('post_image', models.ImageField(upload_to='post_images/')),
            ],
        ),
    ]
